# Generated by Django 4.2.14 on 2025-06-10 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_type', models.CharField(choices=[('Imam', 'Imam'), ('Muazzin', 'Muazzin'), ('Siak', 'Siak')], max_length=20)),
                ('role_id', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('prayer_time', models.CharField(choices=[('Subuh', 'Subuh'), ('Zohor', 'Zohor'), ('Asar', 'Asar'), ('Maghrib', 'Maghrib'), ('Isyak', 'Isyak'), ('Jumaat', 'Jumaat')], max_length=20)),
                ('role_performed', models.CharField(max_length=100)),
                ('attendance_status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DutySchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('prayer_time', models.CharField(choices=[('Subuh', 'Subuh'), ('Zohor', 'Zohor'), ('Asar', 'Asar'), ('Maghrib', 'Maghrib'), ('Isyak', 'Isyak'), ('Jumaat', 'Jumaat')], max_length=20)),
                ('role_type', models.CharField(choices=[('Imam', 'Imam'), ('Muazzin', 'Muazzin'), ('Siak', 'Siak')], max_length=20)),
                ('role_id', models.CharField(max_length=10)),
                ('role_assigned', models.BooleanField(default=True)),
                ('replacement_role_id', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imam',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('ic_number', models.CharField(max_length=12, unique=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('availability', models.BooleanField(default=True)),
                ('imam_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Khutbah',
            fields=[
                ('khutbah_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('event_type', models.CharField(max_length=100)),
                ('khutbah_topic', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_type', models.CharField(choices=[('Imam', 'Imam'), ('Muazzin', 'Muazzin'), ('Siak', 'Siak')], max_length=20)),
                ('role_id', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Muazzin',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('ic_number', models.CharField(max_length=12, unique=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('availability', models.BooleanField(default=True)),
                ('muazzin_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Siak',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('ic_number', models.CharField(max_length=12, unique=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('availability', models.BooleanField(default=True)),
                ('siak_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrayerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('prayer_time', models.CharField(choices=[('Subuh', 'Subuh'), ('Zohor', 'Zohor'), ('Asar', 'Asar'), ('Maghrib', 'Maghrib'), ('Isyak', 'Isyak'), ('Jumaat', 'Jumaat')], max_length=20)),
                ('imam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ImamFlex.imam')),
                ('muazzin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ImamFlex.muazzin')),
                ('siak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ImamFlex.siak')),
            ],
        ),
        migrations.CreateModel(
            name='JumaatPrayer',
            fields=[
                ('jumaat_id', models.AutoField(primary_key=True, serialize=False)),
                ('imam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImamFlex.imam')),
                ('khutbah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImamFlex.khutbah')),
            ],
        ),
    ]
