# Generated by Django 4.2.14 on 2025-06-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImamFlex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imam',
            name='password',
            field=models.CharField(default='imam123', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='muazzin',
            name='password',
            field=models.CharField(default='bilal123', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siak',
            name='password',
            field=models.CharField(default='siak123', max_length=20),
            preserve_default=False,
        ),
    ]
