# Generated by Django 4.2.14 on 2025-06-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImamFlex', '0002_imam_password_muazzin_password_siak_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='imam',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='muazzin',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siak',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
