# Generated by Django 4.2.14 on 2025-06-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImamFlex', '0003_imam_address_muazzin_address_siak_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='leave_docs/'),
        ),
    ]
