# Generated by Django 4.2.14 on 2025-07-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImamFlex', '0005_khutbah_khatib'),
    ]

    operations = [
        migrations.AddField(
            model_name='imam',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='muazzin',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='siak',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
