# Generated by Django 4.2.14 on 2025-07-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImamFlex', '0007_leaverequest_prayer_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateField()),
            ],
        ),
    ]
