# Generated by Django 4.2.14 on 2025-07-09 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImamFlex', '0008_specialnotice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialnotice',
            name='created_at',
        ),
        migrations.AddField(
            model_name='specialnotice',
            name='notice_date',
            field=models.DateField(default=datetime.date(2025, 7, 9)),
            preserve_default=False,
        ),
    ]
