# Generated by Django 4.2.14 on 2025-07-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImamFlex', '0009_remove_specialnotice_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialnotice',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
