# Generated by Django 4.2.14 on 2025-07-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImamFlex', '0010_alter_specialnotice_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='imam',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='muazzin',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='siak',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
