# Generated by Django 4.2.14 on 2025-07-10 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImamFlex', '0011_imam_profile_picture_muazzin_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khutbah',
            name='event_type',
        ),
    ]
