# Generated by Django 4.2.14 on 2025-06-27 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ImamFlex', '0004_leaverequest_supporting_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='khutbah',
            name='khatib',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ImamFlex.imam'),
        ),
    ]
